Resources:
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Condition: CreateVpc

  GatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Condition: CreateVpc
    Properties:
      VpcId: ${self:variables.values.VpcId}
      InternetGatewayId: !Ref InternetGateway

  NatGatewayOne:
    Type: AWS::EC2::NatGateway
    Condition: CreateNatGateways
    Properties:
      AllocationId: !GetAtt NatGatewayOneAttachment.AllocationId
      SubnetId: ${self:variables.values.PublicSubnetOne}

  NatGatewayOneAttachment:
    Type: AWS::EC2::EIP
    Condition: CreateNatGateways
    DependsOn: GatewayAttachment
    Properties:
      Domain: vpc

  NatGatewayTwo:
    Type: AWS::EC2::NatGateway
    Condition: CreateNatGateways
    Properties:
      AllocationId: !GetAtt NatGatewayTwoAttachment.AllocationId
      SubnetId: ${self:variables.values.PublicSubnetTwo}

  NatGatewayTwoAttachment:
    Type: AWS::EC2::EIP
    Condition: CreateNatGateways
    DependsOn: GatewayAttachment
    Properties:
      Domain: vpc
