version: "3.9"

services:
  postgresql:
    extends:
      file: ./postgres/compose.yml
      service: postgresql
    networks:
      - local-net

  pgadmin:
    extends:
      file: ./postgres/compose.yml
      service: pgadmin
    networks:
      - local-net

networks:
  local-net:
    driver: bridge

volumes:
  postgres-data:
    name: postgres-data
