Resources:
  PrivateRouteOne:
    Type: AWS::EC2::Route
    Condition: CreateNatGateways
    Properties:
      RouteTableId: !Ref PrivateRouteTableOne
      DestinationCidrBlock: "0.0.0.0/0"
      NatGatewayId: !Ref NatGatewayOne

  PrivateRouteTableOne:
    Type: AWS::EC2::RouteTable
    Condition: CreateNetworkResources
    Properties:
      VpcId: ${self:variables.values.VpcId}

  PrivateRouteTwo:
    Type: AWS::EC2::Route
    Condition: CreateNatGateways
    Properties:
      RouteTableId: !Ref PrivateRouteTableTwo
      DestinationCidrBlock: "0.0.0.0/0"
      NatGatewayId: !Ref NatGatewayTwo

  PrivateRouteTableTwo:
    Type: AWS::EC2::RouteTable
    Condition: CreateNetworkResources
    Properties:
      VpcId: ${self:variables.values.VpcId}

  PublicRoute:
    Type: AWS::EC2::Route
    Condition: CreateVpc
    DependsOn: GatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: "0.0.0.0/0"
      GatewayId: !Ref InternetGateway

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Condition: CreateVpc
    Properties:
      VpcId: ${self:variables.values.VpcId}
