name: Plyground Deployment to GitHub Pages

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - apps/playground/**

jobs:
  linter:
    name: Linter
    uses: ./.github/workflows/lint.yml

  deploy:
    needs:
      - linter

    runs-on: ubuntu-latest

    concurrency: deployment

    steps:
      - name: Begin CI...
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          registry-url: "https://npm.pkg.github.com"
          scope: "@nanlabs"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v3
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Copy the .npmrc file to the HOME directory and to the project directory
        run: cp $NPM_CONFIG_USERCONFIG $HOME/.npmrc && cp $NPM_CONFIG_USERCONFIG .npmrc

      - name: Install dependencies
        run: npm install

      - name: Build page
        run: npm run build-storybook -w @nanlabs/playground

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./apps/playground/storybook-static
